-- Phase 3: Problem Solving Engine Schema

-- Coding Questions Table
CREATE TABLE IF NOT EXISTS public.coding_questions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    skill_id UUID REFERENCES public.skills(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    difficulty TEXT CHECK (difficulty IN ('Easy', 'Medium', 'Hard')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for coding_questions
ALTER TABLE public.coding_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view coding questions" ON public.coding_questions FOR SELECT USING (true);
-- Only assistants/system can insert? For now allow authenticated users to insert (e.g. generated by AI on behalf of user)
CREATE POLICY "Authenticated users can insert coding questions" ON public.coding_questions FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Test Cases Table
CREATE TABLE IF NOT EXISTS public.test_cases (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    question_id UUID REFERENCES public.coding_questions(id) ON DELETE CASCADE NOT NULL,
    input TEXT NOT NULL,
    expected_output TEXT NOT NULL,
    is_hidden BOOLEAN DEFAULT FALSE
);

-- Enable RLS for test_cases
ALTER TABLE public.test_cases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view test cases" ON public.test_cases FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert test cases" ON public.test_cases FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Code Submissions Table
CREATE TABLE IF NOT EXISTS public.code_submissions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    question_id UUID REFERENCES public.coding_questions(id) ON DELETE CASCADE NOT NULL,
    code TEXT NOT NULL,
    language TEXT NOT NULL DEFAULT 'python',
    status TEXT CHECK (status IN ('pending', 'passed', 'failed', 'error')),
    output TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for code_submissions
ALTER TABLE public.code_submissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own submissions" ON public.code_submissions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own submissions" ON public.code_submissions FOR INSERT WITH CHECK (auth.uid() = user_id);
